name: Fly Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy ${{ matrix.app }}
    runs-on: ubuntu-latest
    concurrency: deploy-${{ matrix.app }}
    strategy:
      matrix:
        include:
          - app: cordelia-boot1
            config: fly-boot1.toml
            region: lhr
          - app: cordelia-boot2
            config: fly-boot2.toml
            region: ams
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: superfly/flyctl-actions/setup-flyctl@63da3ecc5e2793b98a3f2519b3d75d4f4c11cec2 # master

      - name: Deploy ${{ matrix.app }}
        run: flyctl deploy --config ${{ matrix.config }} --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
